// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9Qk_ynapCTXoekjsSD0jfsOqEiBbpi3k',
    appId: '1:956784528470:web:6412698ee6bae3787e7ff7',
    messagingSenderId: '956784528470',
    projectId: 'agentswipe-d9e32',
    authDomain: 'agentswipe-d9e32.firebaseapp.com',
    storageBucket: 'agentswipe-d9e32.firebasestorage.app',
    measurementId: 'G-D2KPG638XK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZJfmG6TTq_jCkZoef7am3LD8ZxxxiJEo',
    appId: '1:956784528470:android:3b20750d097386cb7e7ff7',
    messagingSenderId: '956784528470',
    projectId: 'agentswipe-d9e32',
    storageBucket: 'agentswipe-d9e32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBImtupcoM3v6saZkyMbSSZ3KQzxfVJ9kg',
    appId: '1:956784528470:ios:8fe2e46d3411ff327e7ff7',
    messagingSenderId: '956784528470',
    projectId: 'agentswipe-d9e32',
    storageBucket: 'agentswipe-d9e32.firebasestorage.app',
    iosClientId: '956784528470-f9h4b9o3kmq6b0tif009ikafmphku3s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.propmeet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBImtupcoM3v6saZkyMbSSZ3KQzxfVJ9kg',
    appId: '1:956784528470:ios:8fe2e46d3411ff327e7ff7',
    messagingSenderId: '956784528470',
    projectId: 'agentswipe-d9e32',
    storageBucket: 'agentswipe-d9e32.firebasestorage.app',
    iosClientId: '956784528470-f9h4b9o3kmq6b0tif009ikafmphku3s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.propmeet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9Qk_ynapCTXoekjsSD0jfsOqEiBbpi3k',
    appId: '1:956784528470:web:8401a32c417515bb7e7ff7',
    messagingSenderId: '956784528470',
    projectId: 'agentswipe-d9e32',
    authDomain: 'agentswipe-d9e32.firebaseapp.com',
    storageBucket: 'agentswipe-d9e32.firebasestorage.app',
    measurementId: 'G-B94GQ8G32B',
  );
}
